### ISSUE TITLE
Creating database.yml should be optional

### ISSUE THREAD

**Issue by plu** [poise/application_ruby#67]
My `database.yml` looks something like this, according to http://12factor.net

```yaml
default: &default
  adapter:  <%= ENV['RAILS_DB_ADAPTER'] %>
  encoding: <%= ENV['RAILS_DB_ENCODING'] %>
  database: <%= ENV['RAILS_DB_DATABASE'] %>
  host:     <%= ENV['RAILS_DB_HOST'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
  pool:     <%= ENV['RAILS_DB_POOL'] %>
  username: <%= ENV['RAILS_DB_USERNAME'] %>
```

So it would be cool if I could instruct the `application_ruby` cookbook to not overwrite it. I'm injecting the necessary variables via the environment.

If you think this makes sense, I'll prepare a pull request for that.

Thanks,
plu
